#!/bin/bash
# TODO: Integrate wth CMake soon
run_test () {
    DISABLE_BOOTSTRAP=1 ./build/vm_translator $1.vm $1.asm
    ./tools/CPUEmulator.sh $1.tst    
}

echo "Basic Test..."
run_test ./projects/07/MemoryAccess/BasicTest/BasicTest
echo "Pointer Test..."
run_test ./projects/07/MemoryAccess/PointerTest/PointerTest
echo "Static Test..."
run_test ./projects/07/MemoryAccess/StaticTest/StaticTest
echo "Simple Add Test..."
run_test ./projects/07/StackArithmetic/SimpleAdd/SimpleAdd
echo "Stack Test..."
run_test ./projects/07/StackArithmetic/StackTest/StackTest

echo "Basic Loop Test..."
run_test ./projects/08/ProgramFlow/BasicLoop/BasicLoop
echo "Fibonacci Series Test..."
run_test ./projects/08/ProgramFlow/FibonacciSeries/FibonacciSeries
echo "Simple Function Test..."
run_test ./projects/08/FunctionCalls/SimpleFunction/SimpleFunction
echo "Nested Call Test..."
./build/vm_translator ./projects/08/FunctionCalls/NestedCall/ ./projects/08/FunctionCalls/NestedCall/NestedCall.asm
./tools/CPUEmulator.sh ./projects/08/FunctionCalls/NestedCall/NestedCall.tst
echo "Fibonacci Element Test..."
./build/vm_translator ./projects/08/FunctionCalls/FibonacciElement/ ./projects/08/FunctionCalls/FibonacciElement/FibonacciElement.asm
./tools/CPUEmulator.sh ./projects/08/FunctionCalls/FibonacciElement/FibonacciElement.tst
echo "Statics Test..."
./build/vm_translator  ./projects/08/FunctionCalls/StaticsTest/ ./projects/08/FunctionCalls/StaticsTest/StaticsTest.asm
./tools/CPUEmulator.sh ./projects/08/FunctionCalls/StaticsTest/StaticsTest.tst
